clear; clc; close all;

matlabRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(matlabRoot);
paths = corpus_paths();

% SIMULINK MODEL BUILDER:
% Creates and runs a Simulink model for the final prison RF sensor pipeline.
% The model reads a true drone path and noise signals, then performs:
% Friis received power -> directional detection -> AoA/RSSI localisation ->
% error and alert calculation.

datasetPath = fullfile(paths.simulink, 'simulink_fence24_directional_dataset.mat');
if ~isfile(datasetPath)
    fprintf("Dataset not found. Running prepare_simulink_fence24_dataset first...\n");
    prepare_simulink_fence24_dataset;
end

S = load(datasetPath);
names = fieldnames(S);
for i = 1:numel(names)
    assignin("base", names{i}, S.(names{i}));
end

modelName = "prison_rf_sensor_localisation_model";
modelPath = fullfile(paths.models, modelName + ".slx");

if bdIsLoaded(modelName)
    try
        close_system(modelName, 0);
    catch
        bdclose(modelName);
    end
end
if isfile(modelPath)
    delete(modelPath);
end

new_system(modelName);
open_system(modelName);

stopTime = max(S.sim_time);
set_param(modelName, ...
    "StopTime", num2str(stopTime), ...
    "Solver", "FixedStepDiscrete", ...
    "FixedStep", "1", ...
    "ReturnWorkspaceOutputs", "on");

add_block("simulink/Sources/From Workspace", modelName + "/True X", ...
    "VariableName", "true_x_signal", "Position", [70 80 190 110]);
add_block("simulink/Sources/From Workspace", modelName + "/True Y", ...
    "VariableName", "true_y_signal", "Position", [70 130 190 160]);
add_block("simulink/Sources/From Workspace", modelName + "/True Z", ...
    "VariableName", "true_z_signal", "Position", [70 180 190 210]);
add_block("simulink/Sources/From Workspace", modelName + "/RSSI Noise Vector", ...
    "VariableName", "rssi_noise_signal", "Position", [70 240 190 270]);
add_block("simulink/Sources/From Workspace", modelName + "/AoA Noise Vector", ...
    "VariableName", "aoa_noise_signal", "Position", [70 290 190 320]);

add_block("simulink/User-Defined Functions/MATLAB Function", modelName + "/RF Sensor Network Localisation", ...
    "Position", [310 105 610 305]);

rt = sfroot;
chart = rt.find("-isa", "Stateflow.EMChart", "Path", modelName + "/RF Sensor Network Localisation");
chartCode = getLocalisationBlockCode();
if isstring(chartCode)
    chartCode = char(join(chartCode, ""));
end
chart.Script = chartCode;

add_block("simulink/Sinks/To Workspace", modelName + "/Estimated X", ...
    "VariableName", "simout_estimated_x", "SaveFormat", "Timeseries", "Position", [760 70 890 100]);
add_block("simulink/Sinks/To Workspace", modelName + "/Estimated Y", ...
    "VariableName", "simout_estimated_y", "SaveFormat", "Timeseries", "Position", [760 120 890 150]);
add_block("simulink/Sinks/To Workspace", modelName + "/Error m", ...
    "VariableName", "simout_error_m", "SaveFormat", "Timeseries", "Position", [760 170 890 200]);
add_block("simulink/Sinks/To Workspace", modelName + "/Detection Count", ...
    "VariableName", "simout_detection_count", "SaveFormat", "Timeseries", "Position", [760 220 890 250]);
add_block("simulink/Sinks/To Workspace", modelName + "/Confirmed Detection", ...
    "VariableName", "simout_confirmed_detection", "SaveFormat", "Timeseries", "Position", [760 270 890 300]);
add_block("simulink/Sinks/To Workspace", modelName + "/Alert Before Boundary", ...
    "VariableName", "simout_alert_before_boundary", "SaveFormat", "Timeseries", "Position", [760 320 890 350]);

add_line(modelName, "True X/1", "RF Sensor Network Localisation/1", "autorouting", "on");
add_line(modelName, "True Y/1", "RF Sensor Network Localisation/2", "autorouting", "on");
add_line(modelName, "True Z/1", "RF Sensor Network Localisation/3", "autorouting", "on");
add_line(modelName, "RSSI Noise Vector/1", "RF Sensor Network Localisation/4", "autorouting", "on");
add_line(modelName, "AoA Noise Vector/1", "RF Sensor Network Localisation/5", "autorouting", "on");

add_line(modelName, "RF Sensor Network Localisation/1", "Estimated X/1", "autorouting", "on");
add_line(modelName, "RF Sensor Network Localisation/2", "Estimated Y/1", "autorouting", "on");
add_line(modelName, "RF Sensor Network Localisation/3", "Error m/1", "autorouting", "on");
add_line(modelName, "RF Sensor Network Localisation/4", "Detection Count/1", "autorouting", "on");
add_line(modelName, "RF Sensor Network Localisation/5", "Confirmed Detection/1", "autorouting", "on");
add_line(modelName, "RF Sensor Network Localisation/6", "Alert Before Boundary/1", "autorouting", "on");

save_system(modelName, modelPath);

simOut = sim(modelName);

estimatedX = simOut.get("simout_estimated_x");
estimatedY = simOut.get("simout_estimated_y");
errorM = simOut.get("simout_error_m");
detectionCount = simOut.get("simout_detection_count");
confirmedDetection = simOut.get("simout_confirmed_detection");
alertBeforeBoundary = simOut.get("simout_alert_before_boundary");

resultTime = estimatedX.Time;
resultTable = table();
resultTable.sim_time = resultTime;
resultTable.true_x = interp1(S.true_x_signal(:, 1), S.true_x_signal(:, 2), resultTime, "previous", "extrap");
resultTable.true_y = interp1(S.true_y_signal(:, 1), S.true_y_signal(:, 2), resultTime, "previous", "extrap");
resultTable.estimated_x = estimatedX.Data(:);
resultTable.estimated_y = estimatedY.Data(:);
resultTable.error_m = errorM.Data(:);
resultTable.detection_count = detectionCount.Data(:);
resultTable.confirmed_detection = confirmedDetection.Data(:);
resultTable.alert_before_boundary = alertBeforeBoundary.Data(:);

resultCsv = fullfile(paths.simulink, 'simulink_fence24_directional_model_results.csv');
summaryCsv = fullfile(paths.simulink, 'simulink_fence24_directional_model_summary.csv');
writetable(resultTable, resultCsv);

validErrors = resultTable.error_m(isfinite(resultTable.error_m));
summary = table();
summary.model = string(modelName);
summary.sensor_layout = "fence24_all_directional_120deg";
summary.source_path = "prison_fence24_random_seed1_-60.csv";
summary.total_timestamps = height(resultTable);
summary.localised_timestamps = numel(validErrors);
summary.success_rate_pct = 100 * numel(validErrors) / height(resultTable);
summary.mean_error_m = mean(validErrors);
summary.rmse_error_m = sqrt(mean(validErrors.^2));
summary.median_error_m = median(validErrors);
summary.p95_error_m = prctile(validErrors, 95);
summary.max_error_m = max(validErrors);
summary.pct_below_1m = 100 * mean(validErrors <= 1);
summary.pct_below_2m = 100 * mean(validErrors <= 2);
summary.pct_below_5m = 100 * mean(validErrors <= 5);
summary.mean_detection_count = mean(resultTable.detection_count);
summary.confirmed_detection_rate_pct = 100 * mean(resultTable.confirmed_detection > 0);
summary.alert_before_boundary_rate_pct = 100 * mean(resultTable.alert_before_boundary > 0);
writetable(summary, summaryCsv);

plotSimulinkResults(resultTable);

fprintf("Simulink model saved: %s\n", modelPath);
fprintf("Simulink result CSV saved: %s\n", resultCsv);
fprintf("Simulink summary CSV saved: %s\n", summaryCsv);
disp(summary);

function code = getLocalisationBlockCode()
    code = [
"function [estimated_x, estimated_y, error_m, detection_count, confirmed_detection, alert_before_boundary] = localise(true_x, true_y, true_z, rssi_noise, aoa_noise)" newline ...
"%#codegen" newline ...
"sensorX = [250;250;250;250;250;250;300;400;600;700;750;750;750;750;750;750;700;600;400;300;300;500;700;500];" newline ...
"sensorY = [300;350;450;550;650;700;700;700;700;700;700;650;550;450;350;300;300;300;300;300;500;350;500;650];" newline ...
"sensorZ = 15 * ones(24,1);" newline ...
"orientation = atan2d(sensorY - 500, sensorX - 500);" newline ...
"fov = 120 * ones(24,1);" newline ...
"threshold = -65 * ones(24,1);" newline ...
"frequencyHz = 2.4e9;" newline ...
"txPowerDbm = 20;" newline ...
"txGainDbi = 0;" newline ...
"rxGainDbi = 0;" newline ...
"rssiSigmaDb = 1;" newline ...
"aoaSigmaDeg = 0.5;" newline ...
"rxNoisy = zeros(24,1);" newline ...
"measuredBearing = zeros(24,1);" newline ...
"detected = false(24,1);" newline ...
"detection_count = 0;" newline ...
"for s = 1:24" newline ...
"    dx = true_x - sensorX(s);" newline ...
"    dy = true_y - sensorY(s);" newline ...
"    dz = true_z - sensorZ(s);" newline ...
"    distance = max(sqrt(dx*dx + dy*dy + dz*dz), 1);" newline ...
"    pathLossDb = 20 * log10(distance) + 20 * log10(frequencyHz) - 147.55;" newline ...
"    rxIdeal = txPowerDbm + txGainDbi + rxGainDbi - pathLossDb;" newline ...
"    rxNoisy(s) = rxIdeal + rssi_noise(s);" newline ...
"    trueBearing = atan2d(dy, dx);" newline ...
"    measuredBearing(s) = wrap180Local(trueBearing + aoa_noise(s));" newline ...
"    angleFromBoresight = wrap180Local(trueBearing - orientation(s));" newline ...
"    detected(s) = abs(angleFromBoresight) <= fov(s)/2 && rxNoisy(s) >= threshold(s);" newline ...
"    if detected(s)" newline ...
"        detection_count = detection_count + 1;" newline ...
"    end" newline ...
"end" newline ...
"confirmed_detection = double(detection_count >= 2);" newline ...
"outsideSecureWall = true_x < 300 || true_x > 700 || true_y < 350 || true_y > 650;" newline ...
"alert_before_boundary = double(confirmed_detection > 0 && outsideSecureWall);" newline ...
"estimated_x = NaN;" newline ...
"estimated_y = NaN;" newline ...
"error_m = NaN;" newline ...
"if detection_count < 2" newline ...
"    return;" newline ...
"end" newline ...
"sensorXd = zeros(24,1); sensorYd = zeros(24,1); ranges = zeros(24,1); bearingsRad = zeros(24,1); rangeStd = zeros(24,1);" newline ...
"n = 0;" newline ...
"for s = 1:24" newline ...
"    if detected(s)" newline ...
"        n = n + 1;" newline ...
"        sensorXd(n) = sensorX(s);" newline ...
"        sensorYd(n) = sensorY(s);" newline ...
"        ranges(n) = 10^((txPowerDbm + txGainDbi + rxGainDbi - rxNoisy(s) - 20*log10(frequencyHz) + 147.55)/20);" newline ...
"        bearingsRad(n) = measuredBearing(s) * pi / 180;" newline ...
"        rangeStd(n) = max((log(10)/20) * rssiSigmaDb * ranges(n), 1);" newline ...
"    end" newline ...
"end" newline ...
"pos = [0; 0];" newline ...
"for i = 1:n" newline ...
"    pos(1) = pos(1) + sensorXd(i) + ranges(i) * cos(bearingsRad(i));" newline ...
"    pos(2) = pos(2) + sensorYd(i) + ranges(i) * sin(bearingsRad(i));" newline ...
"end" newline ...
"pos = pos / n;" newline ...
"bearingStd = max(aoaSigmaDeg, 0.1) * pi / 180;" newline ...
"for iter = 1:25" newline ...
"    H = zeros(2,2);" newline ...
"    g = zeros(2,1);" newline ...
"    for i = 1:n" newline ...
"        dx = pos(1) - sensorXd(i);" newline ...
"        dy = pos(2) - sensorYd(i);" newline ...
"        predictedRange = max(sqrt(dx*dx + dy*dy), 1e-6);" newline ...
"        predictedBearing = atan2(dy, dx);" newline ...
"        rr = predictedRange - ranges(i);" newline ...
"        Jr = [dx/predictedRange, dy/predictedRange];" newline ...
"        wr = 1 / rangeStd(i);" newline ...
"        rb = wrapPiLocal(predictedBearing - bearingsRad(i));" newline ...
"        Jb = [-dy/(predictedRange*predictedRange), dx/(predictedRange*predictedRange)];" newline ...
"        wb = 1 / bearingStd;" newline ...
"        H = H + (Jr' * Jr) * wr * wr + (Jb' * Jb) * wb * wb;" newline ...
"        g = g + Jr' * rr * wr * wr + Jb' * rb * wb * wb;" newline ...
"    end" newline ...
"    step = -((H + 1e-5 * eye(2)) \ g);" newline ...
"    pos = pos + step;" newline ...
"    if sqrt(step(1)*step(1) + step(2)*step(2)) < 1e-4" newline ...
"        break;" newline ...
"    end" newline ...
"end" newline ...
"estimated_x = pos(1);" newline ...
"estimated_y = pos(2);" newline ...
"error_m = sqrt((estimated_x - true_x)^2 + (estimated_y - true_y)^2);" newline ...
"end" newline ...
"function angle = wrap180Local(angle)" newline ...
"angle = mod(angle + 180, 360) - 180;" newline ...
"end" newline ...
"function angle = wrapPiLocal(angle)" newline ...
"angle = mod(angle + pi, 2*pi) - pi;" newline ...
"end" newline ...
    ];
end

function plotSimulinkResults(resultTable)
    paths = corpus_paths();
    pathPng = fullfile(paths.figures, 'simulink_fence24_true_vs_estimated_path.png');
    errorPng = fullfile(paths.figures, 'simulink_fence24_error_over_time.png');
    countPng = fullfile(paths.figures, 'simulink_fence24_detection_count.png');

    figure("Position", [100 100 980 560]);
    hTrue = plot(resultTable.true_x, resultTable.true_y, "b-", "LineWidth", 1.5); hold on; grid on; axis equal;
    valid = isfinite(resultTable.estimated_x) & isfinite(resultTable.estimated_y);
    hEstimate = scatter(resultTable.estimated_x(valid), resultTable.estimated_y(valid), 28, resultTable.error_m(valid), "filled");
    rectangle("Position", [250 300 500 400], "EdgeColor", [0.45 0.45 0.45], "LineStyle", "--", "LineWidth", 1.2);
    rectangle("Position", [300 350 400 300], "EdgeColor", "k", "LineWidth", 2);
    hFence = plot(nan, nan, "--", "Color", [0.45 0.45 0.45], "LineWidth", 1.2);
    hWall = plot(nan, nan, "-", "Color", "k", "LineWidth", 2);
    xlim([0 900]);
    ylim([120 760]);
    colorbar;
    xlabel("x (m)"); ylabel("y (m)");
    title("Simulink: True and Estimated Drone Path");
    legend([hTrue, hEstimate, hFence, hWall], ...
        ["True drone path", "Estimated positions", "Outer fence", "Secure wall"], ...
        "Location", "bestoutside");
    exportgraphics(gcf, pathPng, "Resolution", 200);

    figure("Position", [100 100 820 460]);
    plot(resultTable.sim_time, resultTable.error_m, "r.-", "LineWidth", 1.2); grid on;
    xlabel("Simulation time (s)"); ylabel("Localisation error (m)");
    title("Simulink: Localisation Error Over Time");
    exportgraphics(gcf, errorPng, "Resolution", 200);

    figure("Position", [100 100 820 460]);
    stairs(resultTable.sim_time, resultTable.detection_count, "k", "LineWidth", 1.2); grid on;
    xlabel("Simulation time (s)"); ylabel("Number of detecting sensors");
    title("Simulink: Directional Sensors Above Threshold");
    exportgraphics(gcf, countPng, "Resolution", 200);
end
