clear; clc; close all;

matlabRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(matlabRoot);
paths = corpus_paths();

% SIMULINK HYBRID-KALMAN MODEL BUILDER:
% Creates a second Simulink model for the tuned hybrid availability/tracking
% case. This model does not replace the all-directional accuracy model.

datasetPath = fullfile(paths.simulink, 'simulink_hybrid_kalman_dataset.mat');
if ~isfile(datasetPath)
    fprintf("Dataset not found. Running prepare_simulink_hybrid_kalman_dataset first...\n");
    prepare_simulink_hybrid_kalman_dataset;
end

S = load(datasetPath);
names = fieldnames(S);
for i = 1:numel(names)
    assignin("base", names{i}, S.(names{i}));
end

modelName = "prison_rf_hybrid_kalman_model";
modelPath = fullfile(paths.models, modelName + ".slx");

if bdIsLoaded(modelName)
    try
        close_system(modelName, 0);
    catch
        bdclose(modelName);
    end
end
if isfile(modelPath)
    delete(modelPath);
end

new_system(modelName);
open_system(modelName);
set_param(modelName, ...
    "StopTime", num2str(max(S.sim_time)), ...
    "Solver", "FixedStepDiscrete", ...
    "FixedStep", "1", ...
    "ReturnWorkspaceOutputs", "on");

add_block("simulink/Sources/From Workspace", modelName + "/True X", ...
    "VariableName", "true_x_signal", "Position", [70 80 190 110]);
add_block("simulink/Sources/From Workspace", modelName + "/True Y", ...
    "VariableName", "true_y_signal", "Position", [70 130 190 160]);
add_block("simulink/Sources/From Workspace", modelName + "/True Z", ...
    "VariableName", "true_z_signal", "Position", [70 180 190 210]);
add_block("simulink/Sources/From Workspace", modelName + "/RSSI Noise Vector", ...
    "VariableName", "rssi_noise_signal", "Position", [70 240 190 270]);
add_block("simulink/Sources/From Workspace", modelName + "/AoA Noise Vector", ...
    "VariableName", "aoa_noise_signal", "Position", [70 290 190 320]);

add_block("simulink/User-Defined Functions/MATLAB Function", modelName + "/Hybrid RF Sensor Network + Tuned Kalman", ...
    "Position", [310 105 650 315]);
rt = sfroot;
chart = rt.find("-isa", "Stateflow.EMChart", "Path", modelName + "/Hybrid RF Sensor Network + Tuned Kalman");
chartCode = getHybridKalmanBlockCode();
if isstring(chartCode)
    chartCode = char(join(chartCode, ""));
end
chart.Script = chartCode;
configureChartData(chart);

sinkNames = ["Kalman X", "Kalman Y", "Kalman Error m", "Detection Count", ...
    "Confirmed Detection", "Alert Before Boundary", "Raw Error m", "Measurement Update"];
varNames = ["simout_hybrid_kalman_x", "simout_hybrid_kalman_y", "simout_hybrid_kalman_error_m", ...
    "simout_hybrid_detection_count", "simout_hybrid_confirmed_detection", ...
    "simout_hybrid_alert_before_boundary", "simout_hybrid_raw_error_m", "simout_hybrid_measurement_update"];
for i = 1:numel(sinkNames)
    add_block("simulink/Sinks/To Workspace", modelName + "/" + sinkNames(i), ...
        "VariableName", varNames(i), "SaveFormat", "Timeseries", ...
        "Position", [810 55 + 45*i 965 85 + 45*i]);
end

add_line(modelName, "True X/1", "Hybrid RF Sensor Network + Tuned Kalman/1", "autorouting", "on");
add_line(modelName, "True Y/1", "Hybrid RF Sensor Network + Tuned Kalman/2", "autorouting", "on");
add_line(modelName, "True Z/1", "Hybrid RF Sensor Network + Tuned Kalman/3", "autorouting", "on");
add_line(modelName, "RSSI Noise Vector/1", "Hybrid RF Sensor Network + Tuned Kalman/4", "autorouting", "on");
add_line(modelName, "AoA Noise Vector/1", "Hybrid RF Sensor Network + Tuned Kalman/5", "autorouting", "on");
for i = 1:numel(sinkNames)
    add_line(modelName, "Hybrid RF Sensor Network + Tuned Kalman/" + i, sinkNames(i) + "/1", "autorouting", "on");
end

save_system(modelName, modelPath);
simOut = sim(modelName);

kalmanX = simOut.get("simout_hybrid_kalman_x");
kalmanY = simOut.get("simout_hybrid_kalman_y");
kalmanError = simOut.get("simout_hybrid_kalman_error_m");
detectionCount = simOut.get("simout_hybrid_detection_count");
confirmedDetection = simOut.get("simout_hybrid_confirmed_detection");
alertBeforeBoundary = simOut.get("simout_hybrid_alert_before_boundary");
rawError = simOut.get("simout_hybrid_raw_error_m");
measurementUpdate = simOut.get("simout_hybrid_measurement_update");

resultTable = table();
resultTable.sim_time = kalmanX.Time;
resultTable.true_x = interp1(S.true_x_signal(:, 1), S.true_x_signal(:, 2), kalmanX.Time, "previous", "extrap");
resultTable.true_y = interp1(S.true_y_signal(:, 1), S.true_y_signal(:, 2), kalmanX.Time, "previous", "extrap");
resultTable.kalman_x = kalmanX.Data(:);
resultTable.kalman_y = kalmanY.Data(:);
resultTable.kalman_error_m = kalmanError.Data(:);
resultTable.raw_error_m = rawError.Data(:);
resultTable.detection_count = detectionCount.Data(:);
resultTable.confirmed_detection = confirmedDetection.Data(:);
resultTable.alert_before_boundary = alertBeforeBoundary.Data(:);
resultTable.measurement_update = measurementUpdate.Data(:);

resultCsv = fullfile(paths.simulink, 'simulink_hybrid_kalman_model_results.csv');
summaryCsv = fullfile(paths.simulink, 'simulink_hybrid_kalman_model_summary.csv');
writetable(resultTable, resultCsv);

valid = resultTable.kalman_error_m(isfinite(resultTable.kalman_error_m));
summary = table();
summary.model = string(modelName);
summary.sensor_layout = "fence24_hybrid_16_directional_8_omni";
summary.source_path = "prison_fence24_random_seed4_-60.csv";
summary.threshold_dbm = -70;
summary.omni_weight = 0.02;
summary.kalman_accel_std = 0.2;
summary.kalman_measurement_std = 3;
summary.kalman_gate_m = 80;
summary.total_timestamps = height(resultTable);
summary.tracked_timestamps = numel(valid);
summary.tracking_rate_pct = 100 * numel(valid) / height(resultTable);
summary.mean_error_m = mean(valid);
summary.rmse_error_m = sqrt(mean(valid.^2));
summary.median_error_m = median(valid);
summary.p95_error_m = prctile(valid, 95);
summary.pct_below_1m = 100 * mean(valid <= 1);
summary.pct_below_2m = 100 * mean(valid <= 2);
summary.pct_below_5m = 100 * mean(valid <= 5);
summary.mean_detection_count = mean(resultTable.detection_count);
summary.measurement_update_rate_pct = 100 * mean(resultTable.measurement_update > 0);
writetable(summary, summaryCsv);

plotHybridKalmanSimulinkResults(resultTable);

fprintf("Hybrid-Kalman Simulink model saved: %s\n", modelPath);
fprintf("Hybrid-Kalman Simulink result CSV saved: %s\n", resultCsv);
fprintf("Hybrid-Kalman Simulink summary CSV saved: %s\n", summaryCsv);
disp(summary);

function code = getHybridKalmanBlockCode()
    code = [
"function [kalman_x, kalman_y, kalman_error_m, detection_count, confirmed_detection, alert_before_boundary, raw_error_m, measurement_update] = hybridKalman(true_x, true_y, true_z, rssi_noise, aoa_noise)" newline ...
"%#codegen" newline ...
"persistent state P initialised last_x last_y" newline ...
"if isempty(initialised)" newline ...
"    state = zeros(4,1);" newline ...
"    P = diag([100 100 25 25]);" newline ...
"    initialised = false;" newline ...
"    last_x = true_x;" newline ...
"    last_y = true_y;" newline ...
"end" newline ...
"sensorX = [250;250;250;250;250;250;300;400;600;700;750;750;750;750;750;750;700;600;400;300;300;500;700;500];" newline ...
"sensorY = [300;350;450;550;650;700;700;700;700;700;700;650;550;450;350;300;300;300;300;300;500;350;500;650];" newline ...
"sensorZ = 15 * ones(24,1);" newline ...
"sensorType = [1;0;0;0;0;1;0;0;0;0;1;0;0;0;0;1;0;0;0;0;1;1;1;1];" newline ...
"orientation = atan2d(sensorY - 500, sensorX - 500);" newline ...
"fov = 120 * ones(24,1);" newline ...
"threshold = -70;" newline ...
"frequencyHz = 2.4e9;" newline ...
"txPowerDbm = 20;" newline ...
"rssiSigmaDb = 1;" newline ...
"aoaSigmaDeg = 0.5;" newline ...
"omniWeight = 0.02;" newline ...
"accelStd = 0.2;" newline ...
"measStd = 3;" newline ...
"gateM = 80;" newline ...
"rxNoisy = zeros(24,1);" newline ...
"measuredBearing = zeros(24,1);" newline ...
"detected = false(24,1);" newline ...
"detection_count = 0;" newline ...
"directional_count = 0;" newline ...
"for s = 1:24" newline ...
"    dx = true_x - sensorX(s);" newline ...
"    dy = true_y - sensorY(s);" newline ...
"    dz = true_z - sensorZ(s);" newline ...
"    distance = max(sqrt(dx*dx + dy*dy + dz*dz), 1);" newline ...
"    pathLossDb = 20*log10(distance) + 20*log10(frequencyHz) - 147.55;" newline ...
"    rxIdeal = txPowerDbm - pathLossDb;" newline ...
"    rxNoisy(s) = rxIdeal + rssi_noise(s);" newline ...
"    trueBearing = atan2d(dy, dx);" newline ...
"    if sensorType(s) == 1" newline ...
"        inFov = true;" newline ...
"        measuredBearing(s) = 0;" newline ...
"    else" newline ...
"        inFov = abs(wrap180Local(trueBearing - orientation(s))) <= fov(s)/2;" newline ...
"        measuredBearing(s) = wrap180Local(trueBearing + aoa_noise(s));" newline ...
"    end" newline ...
"    detected(s) = inFov && rxNoisy(s) >= threshold;" newline ...
"    if detected(s)" newline ...
"        detection_count = detection_count + 1;" newline ...
"        if sensorType(s) == 0" newline ...
"            directional_count = directional_count + 1;" newline ...
"        end" newline ...
"    end" newline ...
"end" newline ...
"confirmed_detection = double(detection_count >= 2);" newline ...
"outsideSecureWall = true_x < 300 || true_x > 700 || true_y < 350 || true_y > 650;" newline ...
"alert_before_boundary = double(confirmed_detection > 0 && outsideSecureWall);" newline ...
"raw_x = NaN; raw_y = NaN; raw_error_m = NaN;" newline ...
"if directional_count >= 2 || detection_count >= 3 || (directional_count >= 1 && detection_count >= 2)" newline ...
"    sensorXd = zeros(24,1); sensorYd = zeros(24,1); ranges = zeros(24,1); rangeStd = zeros(24,1); bearingRad = zeros(24,1); bearingMask = false(24,1); rangeScale = zeros(24,1);" newline ...
"    n = 0;" newline ...
"    for s = 1:24" newline ...
"        if detected(s)" newline ...
"            n = n + 1;" newline ...
"            sensorXd(n) = sensorX(s);" newline ...
"            sensorYd(n) = sensorY(s);" newline ...
"            ranges(n) = 10^((txPowerDbm - rxNoisy(s) - 20*log10(frequencyHz) + 147.55)/20);" newline ...
"            rangeStd(n) = max((log(10)/20) * rssiSigmaDb * ranges(n), 1);" newline ...
"            if sensorType(s) == 0" newline ...
"                bearingRad(n) = measuredBearing(s) * pi / 180;" newline ...
"                bearingMask(n) = true;" newline ...
"                rangeScale(n) = 1;" newline ...
"            else" newline ...
"                rangeScale(n) = omniWeight;" newline ...
"            end" newline ...
"        end" newline ...
"    end" newline ...
"    pos = [0;0]; countBearing = 0;" newline ...
"    for i = 1:n" newline ...
"        if bearingMask(i)" newline ...
"            countBearing = countBearing + 1;" newline ...
"            pos(1) = pos(1) + sensorXd(i) + ranges(i) * cos(bearingRad(i));" newline ...
"            pos(2) = pos(2) + sensorYd(i) + ranges(i) * sin(bearingRad(i));" newline ...
"        end" newline ...
"    end" newline ...
"    if countBearing > 0" newline ...
"        pos = pos / countBearing;" newline ...
"    else" newline ...
"        for i = 1:n" newline ...
"            pos(1) = pos(1) + sensorXd(i);" newline ...
"            pos(2) = pos(2) + sensorYd(i);" newline ...
"        end" newline ...
"        pos = pos / n;" newline ...
"    end" newline ...
"    bearingStd = aoaSigmaDeg*pi/180;" newline ...
"    for iter = 1:25" newline ...
"        Hmat = zeros(2,2); g = zeros(2,1);" newline ...
"        for i = 1:n" newline ...
"            dx = pos(1) - sensorXd(i);" newline ...
"            dy = pos(2) - sensorYd(i);" newline ...
"            predRange = max(sqrt(dx*dx + dy*dy), 1e-6);" newline ...
"            rr = predRange - ranges(i);" newline ...
"            Jr = [dx/predRange, dy/predRange];" newline ...
"            wr = rangeScale(i) / rangeStd(i);" newline ...
"            Hmat = Hmat + (Jr' * Jr) * wr * wr;" newline ...
"            g = g + Jr' * rr * wr * wr;" newline ...
"            if bearingMask(i)" newline ...
"                predBearing = atan2(dy, dx);" newline ...
"                rb = wrapPiLocal(predBearing - bearingRad(i));" newline ...
"                Jb = [-dy/(predRange*predRange), dx/(predRange*predRange)];" newline ...
"                wb = 1 / bearingStd;" newline ...
"                Hmat = Hmat + (Jb' * Jb) * wb * wb;" newline ...
"                g = g + Jb' * rb * wb * wb;" newline ...
"            end" newline ...
"        end" newline ...
"        step = -((Hmat + 1e-5*eye(2)) \ g);" newline ...
"        pos = pos + step;" newline ...
"        if sqrt(step(1)*step(1)+step(2)*step(2)) < 1e-4" newline ...
"            break;" newline ...
"        end" newline ...
"    end" newline ...
"    raw_x = pos(1); raw_y = pos(2);" newline ...
"    raw_error_m = sqrt((raw_x-true_x)^2 + (raw_y-true_y)^2);" newline ...
"end" newline ...
"dt = max(sqrt((true_x-last_x)^2 + (true_y-last_y)^2) / 15, 1);" newline ...
"if initialised" newline ...
"    F = [1 0 dt 0; 0 1 0 dt; 0 0 1 0; 0 0 0 1];" newline ...
"    q = accelStd^2;" newline ...
"    Q = q * [dt^4/4 0 dt^3/2 0; 0 dt^4/4 0 dt^3/2; dt^3/2 0 dt^2 0; 0 dt^3/2 0 dt^2];" newline ...
"    state = F * state;" newline ...
"    P = F * P * F' + Q;" newline ...
"end" newline ...
"measurement_update = 0;" newline ...
"if ~isnan(raw_x)" newline ...
"    z = [raw_x; raw_y];" newline ...
"    if ~initialised" newline ...
"        state = [raw_x; raw_y; 0; 0];" newline ...
"        initialised = true;" newline ...
"        measurement_update = 1;" newline ...
"    else" newline ...
"        Hk = [1 0 0 0; 0 1 0 0];" newline ...
"        R = (measStd^2) * eye(2);" newline ...
"        residual = z - Hk * state;" newline ...
"        if sqrt(residual(1)^2 + residual(2)^2) <= gateM" newline ...
"            Sk = Hk * P * Hk' + R;" newline ...
"            K = P * Hk' / Sk;" newline ...
"            state = state + K * residual;" newline ...
"            P = (eye(4) - K * Hk) * P;" newline ...
"            measurement_update = 1;" newline ...
"        end" newline ...
"    end" newline ...
"end" newline ...
"if initialised" newline ...
"    kalman_x = state(1);" newline ...
"    kalman_y = state(2);" newline ...
"    kalman_error_m = sqrt((kalman_x-true_x)^2 + (kalman_y-true_y)^2);" newline ...
"else" newline ...
"    kalman_x = NaN; kalman_y = NaN; kalman_error_m = NaN;" newline ...
"end" newline ...
"last_x = true_x; last_y = true_y;" newline ...
"end" newline ...
"function angle = wrap180Local(angle)" newline ...
"angle = mod(angle + 180, 360) - 180;" newline ...
"end" newline ...
"function angle = wrapPiLocal(angle)" newline ...
"angle = mod(angle + pi, 2*pi) - pi;" newline ...
"end" newline ...
    ];
end

function configureChartData(chart)
    data = chart.find('-isa', 'Stateflow.Data');
    for i = 1:numel(data)
        switch data(i).Name
            case {'true_x', 'true_y', 'true_z'}
                data(i).Props.Type.Method = 'Built-in';
                data(i).Props.Type.Primitive = 'double';
                data(i).Props.Array.Size = '1';
            case {'rssi_noise', 'aoa_noise'}
                data(i).Props.Type.Method = 'Built-in';
                data(i).Props.Type.Primitive = 'double';
                data(i).Props.Array.Size = '24';
            otherwise
                if data(i).Scope == "Output"
                    data(i).Props.Type.Method = 'Built-in';
                    data(i).Props.Type.Primitive = 'double';
                    data(i).Props.Array.Size = '1';
                end
        end
    end
end

function plotHybridKalmanSimulinkResults(resultTable)
    paths = corpus_paths();
    pathPng = fullfile(paths.figures, 'simulink_hybrid_kalman_path.png');
    errorPng = fullfile(paths.figures, 'simulink_hybrid_kalman_error_over_time.png');
    countPng = fullfile(paths.figures, 'simulink_hybrid_kalman_detection_count.png');

    figure("Position", [100 100 980 560]);
    hTrue = plot(resultTable.true_x, resultTable.true_y, "b-", "LineWidth", 1.5); hold on; grid on; axis equal;
    valid = isfinite(resultTable.kalman_x) & isfinite(resultTable.kalman_y);
    hEstimate = scatter(resultTable.kalman_x(valid), resultTable.kalman_y(valid), 28, resultTable.kalman_error_m(valid), "filled");
    rectangle("Position", [250 300 500 400], "EdgeColor", [0.45 0.45 0.45], "LineStyle", "--", "LineWidth", 1.2);
    rectangle("Position", [300 350 400 300], "EdgeColor", "k", "LineWidth", 2);
    hFence = plot(nan, nan, "--", "Color", [0.45 0.45 0.45], "LineWidth", 1.2);
    hWall = plot(nan, nan, "-", "Color", "k", "LineWidth", 2);
    xlim([0 900]); ylim([120 760]); colorbar;
    xlabel("x (m)"); ylabel("y (m)");
    title("Simulink Hybrid: Tuned Kalman Tracking");
    legend([hTrue, hEstimate, hFence, hWall], ...
        ["True drone path", "Kalman estimates", "Outer fence", "Secure wall"], ...
        "Location", "bestoutside");
    exportgraphics(gcf, pathPng, "Resolution", 200);

    figure("Position", [100 100 820 460]);
    plot(resultTable.sim_time, resultTable.kalman_error_m, "r-", "LineWidth", 1.2); hold on; grid on;
    plot(resultTable.sim_time, resultTable.raw_error_m, "Color", [0.5 0.5 0.5], "LineStyle", "--", "LineWidth", 1);
    xlabel("Simulation time (s)"); ylabel("Error (m)");
    title("Simulink Hybrid: Raw vs Tuned Kalman Error");
    legend(["Tuned Kalman", "Raw hybrid updates"], "Location", "best");
    exportgraphics(gcf, errorPng, "Resolution", 200);

    figure("Position", [100 100 820 460]);
    stairs(resultTable.sim_time, resultTable.detection_count, "k", "LineWidth", 1.2); grid on;
    xlabel("Simulation time (s)"); ylabel("Number of detecting sensors");
    title("Simulink Hybrid: Detecting Sensors Over Time");
    exportgraphics(gcf, countPng, "Resolution", 200);
end
